### ISSUE TITLE
Alignment issues to resolve

### ISSUE THREAD

**Issue by WendySC25** [WendySC25/BuddyBudget#4]
Current Status:
- Forms and buttons remain in the same position and design as previously defined, thus, alignment issues persist: the current layout conflicts with the overall page design, causing the forms and buttons to be hidden unless the page's viewport is reduced.

<img width="1512" alt="Screenshot 2024-11-26 at 12 54 31 p m" src="https://github.com/user-attachments/assets/f5006b96-511f-48b7-87c7-509d1b08c091">

Next Steps:
- Adjust the alignment and layout to ensure forms and buttons are consistently visible and accessible across different screen sizes.

**Comment by Danna-Olivos** [comment]
Done :)
![Captura desde 2024-11-27 18-17-01](https://github.com/user-attachments/assets/7a191688-50a9-490f-a9c4-e5e80deff617)
![Captura desde 2024-11-27 18-16-55](https://github.com/user-attachments/assets/910fbb41-5c43-468b-9f2c-9f8ea5833b41)
